# Generated by Django 4.1.3 on 2022-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_challenge_likes_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
